
services:

  postgres:
    image: postgres:15
    container_name: cookbook-database
    restart: always
    environment:
      POSTGRES_DB: cookbook_database
      POSTGRES_USER: cookbook_user
      POSTGRES_PASSWORD: cookbook_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cookbook-database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cookbook-app-network

  backend:
    build: ./cookbook-backend
    container_name: cookbook-backend
    ports:
      - "8080:8080"
    networks:
      - cookbook-app-network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./cookbook-frontend
      args:
        VITE_API_URL: http://192.168.1.198:8080
    container_name: cookbook-frontend
    ports:
      - "3000:80"
    networks:
      - cookbook-app-network
    depends_on:
      - backend


networks:
  cookbook-app-network:
    driver: bridge

volumes:
  postgres_data:
